- name: Play1
  hosts: all
  vars:
    URL: vars.google.com
  tasks:
    - name: Variables defined with var
      debug:
        msg: URL = {{URL}}

- name: Play2
  hosts: all
  vars:
    URL: vars.google.com
  tasks:
    - name: Variables defined with var
      debug:
        msg: URL = {{URL}}
      vars:
        URL: vars.url.com

    - name: Variables defined with var
        debug:
          msg: URL = {{URL}}