- name: Play1
  hosts: all
  vars:
    URL: vars.google.com
  tasks:
    - name: Variables defined with var
      debug:
        msg: URL = {{URL}}

- name: Play2
  hosts: all
  vars:
    URL: vars.google.com
  tasks:
    - name: Variables defined with var
      debug:
        msg: URL = {{URL}}
      vars:
        URL: vars.url.com

- name: Play3
  hosts: all
  vars_prompt:
    - name: URL
      prompt: Enter URL
  tasks:
    - name: Prompt from user
      debug:
        msg: URL = {{URL}}