- name: Demo on variables
  hosts: all
  vars:
    URL: vars.google.com
  tasks:
    - name: Variables defined with var
      debug:
        msg: URL = {{URL}}

- name: Demo on variables
  hosts: all
  tasks:
    - name: Variables defined with var
      debug:
        msg: URL = {{URL}}
      vars:
        URL: vars.google.com